// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApiBlog.DbContexts;

#nullable disable

namespace MinimalApiBlog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MinimalApiBlog.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7464b48b-9c62-439c-b5c4-9a465bf944ed"),
                            ContentUrl = "I'm an article",
                            CreatedOn = new DateTime(2023, 9, 2, 15, 58, 10, 263, DateTimeKind.Local).AddTicks(7410),
                            Description = "test article 1",
                            Title = "article 1"
                        },
                        new
                        {
                            Id = new Guid("a77fe743-1f20-46c1-89a8-0d75c75edded"),
                            ContentUrl = "I'm an article",
                            CreatedOn = new DateTime(2023, 9, 2, 15, 58, 10, 263, DateTimeKind.Local).AddTicks(7500),
                            Description = "test article 2",
                            Title = "article 2"
                        },
                        new
                        {
                            Id = new Guid("b90c3da7-8da8-4c2b-884e-eba7c6ac0b39"),
                            ContentUrl = "I'm an article",
                            CreatedOn = new DateTime(2023, 9, 2, 15, 58, 10, 263, DateTimeKind.Local).AddTicks(7510),
                            Description = "test article 3",
                            Title = "article 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
